package Chatserver;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Asus
 */
public class MainFrame extends javax.swing.JFrame {

    private Server sv;
    private String kickorbanmessage;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        sv = new Server(this);
        sv.start();
    }

    public String getKickorbanmessage() {
        return kickorbanmessage;
    }

    public synchronized void append(String str) {
        mainArea.append(str + "\n");
        mainArea.setCaretPosition(mainArea.getDocument().getLength());
    }
    
    public synchronized void appendError(String str) {
        errorArea.append(str + "\n");
        errorArea.setCaretPosition(errorArea.getDocument().getLength());
    }

    public synchronized void imOnline(String user) {
        StringBuilder str = new StringBuilder(onlineArea.getText());
        str.append(user).append("\n");
        onlineArea.setText(str.toString());
    }

    public synchronized void imOffline(String user) {
        String str = onlineArea.getText();
        String[] aux = str.split("\n");
        if (aux.length == 0) {
            onlineArea.setText("");
            return;
        }
        StringBuilder strbuilder = new StringBuilder();
        for (String aux1 : aux) {
            if (!aux1.equals(user)) {
                strbuilder.append(aux1).append("\n");
            }
        }
        onlineArea.setText(strbuilder.toString());
    }

    public synchronized void changeOnlines(String str) {
        onlineArea.setText(str);
    }

    private synchronized void sendMsg() {
        if (!msgField.getText().isEmpty() && !receiverField.getText().isEmpty()) {
            sv.sendServerMsg(new Message(msgField.getText(), "SERVER", receiverField.getText(), Message.Type.MESSAGE));
            msgField.setText("");
            receiverField.setText("");
        } else {
            if (!msgField.getText().isEmpty() && receiverField.getText().isEmpty()) {
                sv.sendServerMsg(new Message(msgField.getText(), "SERVER", "", Message.Type.MESSAGE));
                msgField.setText("");
            }
        }
    }

    private void kickOrBan(String typename, Message.Type type) {
        JTextField name = new JTextField();
        JTextField message = new JTextField();
        Object[] obj = {
            "Client: ", name,
            "Message: ", message
        };
        int opt = JOptionPane.showConfirmDialog(null, obj, typename, JOptionPane.OK_CANCEL_OPTION);
        if (opt == JOptionPane.OK_OPTION) {
            if (!name.getText().isEmpty() && !message.getText().isEmpty()) {
                kickorbanmessage = message.getText();
                sv.sendServerMsg(new Message(message.getText(), "SERVER", name.getText(), type));
            } else {
                JOptionPane.showMessageDialog(null, "Please enter all fields!");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainArea = new javax.swing.JTextArea();
        msgField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        onlineArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        receiverField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kickButton = new javax.swing.JButton();
        BanButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        errorArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setLocation(new java.awt.Point(200, 200));
        setResizable(false);

        mainArea.setEditable(false);
        mainArea.setColumns(20);
        mainArea.setLineWrap(true);
        mainArea.setRows(5);
        jScrollPane1.setViewportView(mainArea);

        msgField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msgFieldKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Message:");

        onlineArea.setEditable(false);
        onlineArea.setColumns(20);
        onlineArea.setLineWrap(true);
        onlineArea.setRows(5);
        onlineArea.setPreferredSize(null);
        jScrollPane2.setViewportView(onlineArea);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("To:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Online");

        kickButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        kickButton.setText("Kick");
        kickButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kickButtonActionPerformed(evt);
            }
        });

        BanButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BanButton.setText("Ban");
        BanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanButtonActionPerformed(evt);
            }
        });

        errorArea.setEditable(false);
        errorArea.setColumns(20);
        errorArea.setLineWrap(true);
        errorArea.setRows(5);
        jScrollPane3.setViewportView(errorArea);

        jMenu1.setText("File");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiverField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msgField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(kickButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BanButton)
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(57, 57, 57)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kickButton)
                            .addComponent(BanButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(receiverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(msgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sendMsg();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void msgFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msgFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            sendMsg();
        }
    }//GEN-LAST:event_msgFieldKeyPressed

    private void kickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kickButtonActionPerformed
        kickOrBan("Kick", Message.Type.KICK);
    }//GEN-LAST:event_kickButtonActionPerformed

    private void BanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanButtonActionPerformed
        kickOrBan("Ban", Message.Type.BAN);
    }//GEN-LAST:event_BanButtonActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BanButton;
    private javax.swing.JTextArea errorArea;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton kickButton;
    private javax.swing.JTextArea mainArea;
    private javax.swing.JTextField msgField;
    private javax.swing.JTextArea onlineArea;
    private javax.swing.JTextField receiverField;
    // End of variables declaration//GEN-END:variables
}
